"""add_roles_and_approval_to_users

Revision ID: 03fb40ca3d19
Revises: 755015e121ab
Create Date: 2026-08-07 19:08:15.140473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fb40ca3d19'
down_revision: Union[str, Sequence[str], None] = '755015e121ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), server_default='operator', nullable=False))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
