"""add_report_status_and_error_fields

Revision ID: 755015e121ab
Revises: 77ccdff63325
Create Date: 2026-08-07 18:32:04.754169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '755015e121ab'
down_revision: Union[str, Sequence[str], None] = '77ccdff63325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_reports', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('voice_reports', sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('voice_reports', 'file_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('voice_reports', 'file_path',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('voice_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_voice_reports_status', table_name='voice_reports')
    op.drop_index('ix_voice_reports_user_id', table_name='voice_reports')
    op.create_index(op.f('ix_voice_reports_id'), 'voice_reports', ['id'], unique=False)
    op.drop_constraint('voice_reports_user_id_fkey', 'voice_reports', type_='foreignkey')
    op.create_foreign_key(None, 'voice_reports', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_reports', type_='foreignkey')
    op.create_foreign_key('voice_reports_user_id_fkey', 'voice_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_voice_reports_id'), table_name='voice_reports')
    op.create_index('ix_voice_reports_user_id', 'voice_reports', ['user_id'], unique=False)
    op.create_index('ix_voice_reports_status', 'voice_reports', ['status'], unique=False)
    op.alter_column('voice_reports', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_reports', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_reports', 'file_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('voice_reports', 'file_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('voice_reports', 'retry_count')
    op.drop_column('voice_reports', 'error_message')
    # ### end Alembic commands ###
