"""create users and voice_reports tables

Revision ID: 77ccdff63325
Revises: 
Create Date: 2026-08-03 23:20:51.925425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ccdff63325'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bale_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bale_user_id'), 'users', ['bale_user_id'], unique=True)
    op.create_table('voice_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_reports_status'), 'voice_reports', ['status'], unique=False)
    op.create_index(op.f('ix_voice_reports_user_id'), 'voice_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_reports_user_id'), table_name='voice_reports')
    op.drop_index(op.f('ix_voice_reports_status'), table_name='voice_reports')
    op.drop_table('voice_reports')
    op.drop_index(op.f('ix_users_bale_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
